---
abstract: 'Official Perl support for all Tinkerforge Bricks and Bricklets'
author:
  - 'Ishraq Ibne Ashraf <ishraq@tinkerforge.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tinkerforge
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_SHA1: 0
  IO::Socket::INET: 0
  Test::More: 0
  Thread::Queue: 3.02
  Thread::Semaphore: 0
  threads: 0
version: v2.1.3
